#!/bin/sh
set -eu

src="${1:-docs/API.generated.md}"
out_dir="${2:-docs/api}"
index="${3:-docs/API.md}"

if [ ! -f "$src" ]; then
    echo "source API document not found: $src" >&2
    exit 1
fi

mkdir -p "$out_dir"
rm -f "$out_dir"/*.md

awk -v out_dir="$out_dir" '
function start_package(name) {
    if (file != "") {
        close(file)
    }
    file = out_dir "/" name ".md"
    print "<!-- Code generated by gomarkdoc. DO NOT EDIT -->" > file
    print "" >> file
    print $0 >> file
}

/^# [A-Za-z0-9_-]+$/ {
    start_package($2)
    next
}

/^Generated by / {
    next
}

file != "" {
    print $0 >> file
}
' "$src"

cat > "$index" <<'EOF'
# API Reference

The API reference is generated from the Go packages under `pkg/` and split by package so each module has its own searchable page.

## Primary Packages

| Package | Description |
|---------|-------------|
| [ticker](api/ticker.md) | Single-symbol quotes, history, financials, options, holders, analysis, news, and valuation data |
| [multi](api/multi.md) | Batch historical downloads for multiple symbols |
| [screener](api/screener.md) | Predefined and custom equity, fund, and ETF screeners |
| [search](api/search.md) | Symbol, company, news, list, and research search |
| [lookup](api/lookup.md) | Ticker lookup by asset type |
| [market](api/market.md) | Market status and summary data |
| [sector](api/sector.md) | Sector overview, companies, industries, ETFs, and funds |
| [industry](api/industry.md) | Industry overview, sector mapping, top companies, and reports |
| [calendars](api/calendars.md) | Earnings, IPO, economic events, and split calendars |
| [live](api/live.md) | Real-time WebSocket pricing stream |

## Support Packages

| Package | Description |
|---------|-------------|
| [models](api/models.md) | Shared request, response, and domain data structures |
| [client](api/client.md) | Yahoo Finance HTTP client, authentication, and typed errors |
| [config](api/config.md) | Global configuration helpers |
| [cache](api/cache.md) | Thread-safe in-memory cache |
| [repair](api/repair.md) | Price data repair primitives |
| [stats](api/stats.md) | Statistical helpers used by repair logic |
| [utils](api/utils.md) | Timezone and MIC/Yahoo ticker suffix helpers |
EOF

echo "Split API docs into $out_dir and wrote $index"
